steps:

  - name: 'python:3.11.11'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        pip install --no-cache-dir dvc dvc-gs
        dvc pull
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Downloading secret..."
        gcloud secrets versions access 1 --secret=env-file > .env  # Replace with your secret details


  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'dockerfiles/api.dockerfile',
      '-t', 'europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model',
      '.'
      
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

