steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model',
      'dockerfiles/',
      'f',
      'api.dockerfile'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

#hye