steps:

  - name: 'python:3.11.11'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        pip install --no-cache-dir dvc dvc-gs
        dvc pull
  - name: Download Secret File
    id: download-secret
    uses: google-github-actions/get-secretmanager-secrets@v1
    with:
      secrets: |
        my-secret:projects/579403182821/secrets/env-file/versions/1 # Replace with your secret details

  - name: Save Secret to File
    run: echo "${{ steps.download-secret.outputs['my-secret'] }}" > .env  # Replace with your desired file path


  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'dockerfiles/api.dockerfile',
      '-t', 'europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model',
      '.'
      
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

