steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/mlops-448109/my-app:$COMMIT_SHA',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/mlops-448109/my-app:$COMMIT_SHA'
    ]

images:
  - 'gcr.io/mlops-448109/my-app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
