model:
  batch_size: 48
  input_path: "data/processed/preprocessed_data.csv"
  output_path: "models/processed_posts_with_sentiment.csv"

train:
  seed: 42
  max_length: 128
  train_split: 0.9
  batch_size: 48
  lr: 6.668800023514091e-05
  l2: 0.0006952061798051868
  lr_min: 1e-7
  lr_max: 1e-3
  l2_min: 1e-6
  l2_max: 1e-3
  optuna_epoch: 5
  final_epoch: 5
  n_trials: 20
  data_path: "data/raw/data.csv"
