
model:
  batch_size: 32

train:
    seed: 42
    max_length: 128
    train_split: 0.01
    batch_size: 32
    lr_min: 1e-7            # Minimum learning rate for tuning
    lr_max: 1e-3            # Maximum learning rate for tuning
    l2_min: 1e-6            # Minimum L2 regularization for tuning
    l2_max: 1e-3
    optuna_epoch: 3
    final_epoch: 5
    n_trials: 1