site_name: reddit_forecast
site_author: Lucas Sylvester
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - API Documentation: my_api.md
  - Frontend: frontend.md
  - Data: data.md
  - Train: train.md
  - Model: model.md
  - How to run: how_to_run.md
