name: Trigger Google Cloud Build

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor
    paths:
      - model_registry/**  # Monitor specific files or directories

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Add this secret to your repository

      - name: Download Secret File
        id: download-secret
        uses: google-github-actions/get-secretmanager-secrets@v1
        with:
          secrets: |
            my-secret:projects/579403182821/secrets/env-file/versions/1 # Replace with your secret details

      - name: Save Secret to File
        run: echo "${{ steps.download-secret.outputs['my-secret'] }}" > .env  # Replace with your desired file path

      - name: Trigger Cloud Build
        id: trigger
        uses: google-github-actions/deploy-cloud-build@v0
        with:
          project_id: mlops-448109  # Your GCP project ID
          trigger_id: 4ad25995-764c-4890-9e73-d8b3fa224bd9  # Replace with the actual trigger ID from Cloud Build
          substitutions: |
            _MODEL_NAME=model  # Optional: Add custom substitutions for your build
