name: Trigger Google Cloud Build

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor
    paths:
      - model_registry/**  # Monitor specific files or directories

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Cloud Build
        id: trigger
        uses: google-github-actions/deploy-cloud-build@v0
        with:
          project_id: mlops-448109  # Your GCP project ID
          trigger_id: your-trigger-id  # Replace with the actual trigger ID from Cloud Build
          substitutions: |
            _MODEL_NAME=model  # Optional: Add custom substitutions for your build
