name: Build Docker Images
#test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_context:
        description: "Docker build context"
        default: "."
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push API image
      - name: Build and Push API Image
        run: |
          docker build -f dockerfiles/api.dockerfile -t ${{ secrets.DOCKER_USERNAME }}/reddit_forecast_api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/reddit_forecast_api:latest

      # Build and push training image
      - name: Build and Push Training Image
        run: |
          docker build -f dockerfiles/train.dockerfile -t ${{ secrets.DOCKER_USERNAME }}/reddit_forecast_train:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/reddit_forecast_train:latest
