name: Build, Push, Cleanup, and Deploy Docker Image for model.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_context:
        description: "Docker build context"
        default: "."
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      #get github secrets and put in .env file
      - name: Set up Environment Variables
        run: |
          echo "REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}" >> .env
          echo "REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}" >> .env
      - name: Get data
        run: |
          pip install dvc
          pip install dvc-gs
          dvc pull --no-run-cache --force --verbose

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Configure Docker for Google Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev      
      # Step 5: Build and push the Docker image
      - name: Build and Push Model Image
        run: |
          docker build -f dockerfiles/api.dockerfile -t europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model:latest .
          docker push europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model:latest
     # Step 4: Cleanup ALL untagged images from Artifact Registry
      - name: Cleanup Untagged Images
        run: |
          echo "Fetching untagged images..."
          # Filter images with empty tags
          UNTAGGED_IMAGES=$(gcloud artifacts docker images list \
              europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry \
              --format="json" | jq -r '.[] | select(.tags == "") | .metadata.name')

          if [ -z "$UNTAGGED_IMAGES" ]; then
            echo "No untagged images found."
            exit 0
          fi

          echo "Found untagged images:"
          echo "$UNTAGGED_IMAGES"

          echo "$UNTAGGED_IMAGES" | while read -r image; do
            # Convert the metadata.name field into the full image path
            CLEANED_IMAGE=$(echo "$image" | sed 's|projects/mlops-448109/locations/europe-west4/repositories/mlops-artifact-registry/dockerImages/|europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/|')

            echo "Attempting to delete untagged image: $CLEANED_IMAGE"

            # Attempt to delete the untagged image
            if ! gcloud artifacts docker images delete "$CLEANED_IMAGE" --quiet; then
              echo "Warning: Failed to delete image $CLEANED_IMAGE. Skipping..."
            fi
          done



      # Step 5: Deploy to Cloud Run with 4GB memory allocation
      - name: Deploy to Cloud Run
        run: |
          gcloud beta run services add-iam-policy-binding reddit-forecast-model \
            --region=europe-west4 \
            --member=allUsers \
            --role=roles/run.invoker

          gcloud run deploy reddit-forecast-model \
            --image europe-west4-docker.pkg.dev/mlops-448109/mlops-artifact-registry/reddit_forecast_model:latest \
            --platform managed \
            --region=europe-west4 \
            --port 8000 \
            --memory 4Gi \
            --allow-unauthenticated
      
      # Step 6: Wait for the service to respond
      - name: Wait for Service to Start
        run: |
          echo "Waiting for the service to respond..."
          SERVICE_URL=$(gcloud run services describe reddit-forecast-model --region europe-west4 --format 'value(status.url)')
          echo "Service URL: $SERVICE_URL"

          MAX_RETRIES=30
          RETRY_COUNT=0
          while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
            # Check if the service responds with HTTP 200
            if curl --silent --fail "$SERVICE_URL" > /dev/null; then
              echo "Service is up and running at $SERVICE_URL"
              break
            fi
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo "Waiting for the application to respond... (retry $RETRY_COUNT/$MAX_RETRIES)"
            sleep 2
          done

          # Exit with an error if the service did not respond
          if [[ $RETRY_COUNT -eq $MAX_RETRIES ]]; then
            echo "Application did not start within the expected time. Please check the Cloud Run logs for issues."
            exit 1
          fi

