name: Data Statistics Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  data-statistics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Get data
        run: |
          pip install dvc
          pip install dvc-gs
          dvc pull --no-run-cache --force --verbose

      - name: Run dataset statistics
        env:
          PYTHONPATH: src
        run: |
          python -c "from reddit_forecast.data import dataset_statistics; from pathlib import Path; dataset_statistics(Path('data/processed'))"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dataset-statistics
          path: data/processed/statistics_report.md
