name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip list

      - name: Install local package
        run: |
          pip install -e .

      - name: Run tests & coverage (Linux and macOS)
        if: matrix.operating-system != 'windows-latest'
        run: |
          PYTHONPATH=src coverage run -m pytest tests/ --strict-markers --disable-warnings
          coverage report -m

      - name: Run tests & coverage (Windows)
        if: matrix.operating-system == 'windows-latest'
        run: |
          $env:PYTHONPATH="src"
          coverage run -m pytest tests/ --strict-markers --disable-warnings
          coverage report -m

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage
