name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip list

      - name: Install local package
        run: |
          pip install -e .

      # MacOS-specific memory optimization
      - name: Optimize memory for macOS
        if: matrix.operating-system == 'macos-latest'
        run: |
          export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
          export PYTORCH_ENABLE_MPS_FALLBACK=1

      # Skip memory-intensive tests on macOS
      - name: Run lightweight tests on macOS
        if: matrix.operating-system == 'macos-latest'
        run: |
          PYTHONPATH=src coverage run -m pytest tests/ --disable-warnings --ignore=tests/test_model.py
          coverage report -m

      - name: Run full tests on other platforms
        if: matrix.operating-system != 'macos-latest'
        run: |
          PYTHONPATH=src coverage run -m pytest tests/ --strict-markers --disable-warnings
          coverage report -m

      # Monitor memory usage (optional, for debugging)
      - name: Monitor memory usage (before tests)
        if: matrix.operating-system == 'macos-latest'
        run: |
          vm_stat

      - name: Monitor memory usage (after tests)
        if: matrix.operating-system == 'macos-latest'
        run: |
          vm_stat

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage

      - name: Run tests & coverage (Windows)
        if: matrix.operating-system == 'windows-latest'
        run: |
          $env:PYTHONPATH="src"
          coverage run -m pytest tests/ --strict-markers --disable-warnings
          coverage report -m

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .coverage
